site_name: openHAB Dokumentation
pages:
- [index.md, Home]
- [Installation.md, Installation auf PC]
- [Beispiel.md, Erste Schritte]
- [KNX.md, KNX Anbindung] 
- [Bindings.md, Bindings]
- [Persistence.md, Persistence]
- [Raspberry.md, Installation auf einem Raspberry PI]
- [setpoint.md, Setpoint Beispiel]
- [Viesmann.md, Kommunikation mit Viesmann Heizung via openHAB]
- [license.md, Lizenzierung]