site_name: openHAB Dokumentation
nav:
- Home: 'index.md'
- 'OpenHAB 2.x Installation auf einem PC': 'openHAB2_Installation.md'
- 'OpenHAB 1.x Installation auf einem PC': 'Installation.md'
- Erste Schritte: 'Beispiel.md'
- Anbindung an den KNX-Bus: 'KNX.md'
- HTTP-Binding: 'Binding_HTTP.md'
- HomeMatic-Binding: 'HomeMatic_YAHM.md'
- Milight-Binding: 'Binding_milight.md'
- Persistence: 'Persistence.md'
- Installation auf einem Raspberry PI: 'Raspberry.md'
# - Autostart von openHAB auf dem Raspberry PI: 'Autostart.md'
- Setpoint Beispiel: 'setpoint.md'
- Anbindung Kostal Wechselrichter: 'Kostal_inverter_HTTP.md'
- Anbindung B-Control Manager: 'B-Control_EM_example.md'
- Anbindung Viessmann Heizung: 'Viessmann.md'
- Lizenzierung: 'license.md'
theme: readthedocs
