site_name: openHAB Dokumentation
pages:
- ['index.md', 'Home']
- ['Installation.md', 'OpenHAB Installation auf einem PC']
- ['Beispiel.md', 'Erste Schritte']
- ['KNX.md', 'Anbindung an den KNX-Bus'] 
- ['Binding_HTTP.md', 'HTTP-Binding']
- ['Persistence.md', 'Persistence']
- ['Raspberry.md', 'Installation auf einem Raspberry PI']
- ['Autostart.md', 'Autostart von openHAB auf dem Raspberry PI']
- ['setpoint.md', 'Setpoint Beispiel']
- ['Viessmann.md', 'Anbindung Viessmann Heizung via openHAB']
- ['license.md', 'Lizenzierung']